services:
  tgi-service:
    image: ghcr.io/huggingface/tgi-gaudi:latest
    container_name: tgi-gaudi-server
    ports:
      - "8085:80"
    volumes:
      - ${HF_CACHE_DIR}:/data
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HF_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      HF_HUB_DISABLE_PROGRESS_BARS: 1
      HF_HUB_ENABLE_HF_TRANSFER: 0
      HABANA_VISIBLE_DEVICES: all
      OMPI_MCA_btl_vader_single_copy_mechanism: none
    runtime: habana
    cap_add:
      - SYS_NICE
    ipc: host
    command: --model-id ${LLM_MODEL_ID} --max-input-length 2048 --max-total-tokens 4096